version: "3.9"

services:
    database:
        image: "mcr.microsoft.com/mssql/server:2017-CU21-ubuntu-16.04"
        ports:
            - "11433:1433"
        environment:
            SA_PASSWORD: "ITsDemos2021"
            ACCEPT_EULA: "Y"
        volumes:
            - database-data:/var/opt/mssql/data

volumes:
  database-data: